"""add program columns and admin table

Revision ID: 3e425b0e2a15
Revises: 97bb83697390
Create Date: 2025-12-18 17:17:36.682391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e425b0e2a15'
down_revision: Union[str, Sequence[str], None] = '97bb83697390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_admins_id'), 'program_admins', ['id'], unique=False)
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.add_column('programs', sa.Column('num_residents_per_class', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('program_length_years', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('blocks_per_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'blocks_per_year')
    op.drop_column('programs', 'program_length_years')
    op.drop_column('programs', 'num_residents_per_class')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.drop_index(op.f('ix_program_admins_id'), table_name='program_admins')
    op.drop_table('program_admins')
    # ### end Alembic commands ###
